### ISSUE TITLE
Login Twig extension requires Session

### ISSUE THREAD

**Issue by David-Guillot** [bitgandtter/GoogleBundle#21]
Hi @bitgandtter ,

I am trying to get my Symfony2 application not to start a session where it isn't needed, but I have a blocker : as soon as this GoogleBundle is loaded in my AppKernel, if I load Twig to render a page, the Twig extensions of this bundle are loaded (because of the "twig.extension" tag), and as one of them requires service "bit_google.client" which itself requires a Symfony2 Session, a session is started.

I see a few ways to handle this situation, and I can implement the solution you will choose among:
* Very easy but not very convenient for your bundle's user: not declaring the Twig extensions services and adding to the bundle's documentation how to enable them
* A bit better: add a boolean configuration parameter (to false by default) to your bundle to enable the Twig extensions, and enable them with a Compiler Pass depending on the value of the configuration parameter
* Change the way the Session is injected to the GoogleClient service to avoid an automatic instantiation, but I'm not really sure how to do this

Please tell me what's your favorite approach (or if you'd use a different one) and I can implement it for you this weekend, as this is a blocker to me in a professional project.

Thanks

**Comment by bitgandtter** [comment]
Hi there. Has been a while since i deprecate this bundle i advice to use the Hwoauthbundle that its more complete on this matter and has a greate documentation. Now if you like it you can take over this bundle and keep maintaining it. 

About the blocker issue. From my perspective the best solution its #2 since #1 as you say is not a good one and #3 is impossible, at far as I know; since once your require to inject the session service on one of your the session will be automatically started. Also SF since version 2.3 autostar session on every request you need to toggle that off on the commit. 

About solution #2 I think to add the configuration parameter is great but I advice to set it on true by default since the aim of the bundle is easy configuration and easy start to use integration. So in the most cases that behavior will apply. For casea like yours you will then have this configuration option to disable the extension. 

Cheera

**Comment by David-Guillot** [comment]
Hello,

So there is PR #22 that fixes the issue. Some information:
* Didn't know this bundle was deprecated, but actually I'm using it for its GoogleContacts feature, so Hwoauthbundle doesn't apply to me ;)
* Symfony2 doesn't autostart sessions, but many people think it does because they use session stuff without noticing (like flash messages in Twig templates for example, or in more complex cases like setting a tag that will make a session-dependent service instantiated on every request)
* I implemented solution 2/ but without Compiler Pass, I just isolated the Twig extension in a separate configuration file that I load only if the configuration parameter is set to true (and yes, true is the default value ;))
* I also changed the symfony components dependencies to make your bundle still compatible with Symfony 2.3 projects :)

So if you have a minute, please consider merging #22 and create a release for this bundle ;)
Thanks
